const sampleIndividualTextAnalysis = {
  "tweet_data": {
    "tweet_id_db": 101,
    "id": 1554405286206705664,
    "conversation_id": "1554405286206705664",
    "created_at": "2022-08-02 09:54:34 UTC",
    "date": "2022-08-02",
    "time": "09:54:34",
    "timezone": "+0000",
    "user_id": 1480749782,
    "username": "macaesbruno",
    "name": "Bruno Maçães",
    "place": "",
    "tweet": "Here is how Indians should understand the war in Ukraine: imagine Britain tomorrow decided India does not exist, it was created by Britain, most people there speak English anyway, so Britain “will solve the Indian problem once and for all”",
    "language": "en",
    "urls": "",
    "photos": "",
    "replies_count": 1,
    "retweets_count": 1,
    "likes_count": 15,
    "hashtags": "",
    "cashtags": "",
    "link": "https://twitter.com/MacaesBruno/status/1554405286206705664",
    "retweet": "",
    "quote_url": "",
    "video": 0,
    "thumbnail": "",
    "near": "",
    "geo": "",
    "source": "",
    "user_rt_id": "",
    "user_rt": "",
    "retweet_id": "",
    "reply_to": "",
    "retweet_date": "2022-08-02T09:58:42.851000Z",
    "translate": "",
    "trans_src": "",
    "trans_dest": "",
    "video_link": "",
    "translated": "",
    "projectId": 78,
    "socialMediaName": "Twitter",
    "prediction": 1,
    "multilabel": "id,related,PII,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,water,food,shelter,clothing,money,missing_people,refugees,death,other_aid,infrastructure_related,transport,buildings,electricity,tools,hospitals,shops,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather",
    "status": "sent",
    "creationTime": "2022-08-02T09:58:42.851000Z",
    "passedFromModel": "True",
    "rank": 0,
    "geolocation_lat": 0.0,
    "geolocation_lng": 0.0,
    "video_link_od": "",
    "video_transcript": "",
    "verdict": 100,
    "videoPrediction": 0
  },
  "tweet_photos": [],
  "tweet_photos_classified": [],
  "tweet_obj_detection": [],
  "tweet_crop_detection": [],
  "tweet_ner": []
}